package ir

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"math/big"
	"reflect"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/Runarry/ProxyLoom/schemas"
	"github.com/santhosh-tekuri/jsonschema/v6"
	"github.com/santhosh-tekuri/jsonschema/v6/kind"
)

const MaxDocumentBytes = 10 * 1024 * 1024
const maxJSONDepth = 128

// parseDocument prevents encoding/json from accepting duplicate keys, multiple
// values, invalid UTF-8 or unpaired UTF-16 escapes with silent data replacement.
func parseDocument(data []byte) (any, error) {
	if len(data) > MaxDocumentBytes || !utf8.Valid(data) || !validSurrogates(data) {
		return nil, Diagnostics{issue(InvalidJSON, "")}
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	value, err := readValue(dec, "", 0)
	if err != nil {
		return nil, err
	}
	if _, err := dec.Token(); err != io.EOF {
		return nil, Diagnostics{issue(InvalidJSON, "")}
	}
	return value, nil
}

func readValue(dec *json.Decoder, path string, depth int) (any, error) {
	if depth > maxJSONDepth {
		return nil, Diagnostics{issue(InvalidJSON, path)}
	}
	token, err := dec.Token()
	if err != nil {
		return nil, Diagnostics{issue(InvalidJSON, path)}
	}
	delim, composite := token.(json.Delim)
	if !composite {
		return token, nil
	}
	switch delim {
	case '{':
		value := make(map[string]any)
		for dec.More() {
			keyToken, err := dec.Token()
			if err != nil {
				return nil, Diagnostics{issue(InvalidJSON, path)}
			}
			key, ok := keyToken.(string)
			if !ok {
				return nil, Diagnostics{issue(InvalidJSON, path)}
			}
			childPath := safeChildPath(path, key)
			if _, exists := value[key]; exists {
				return nil, Diagnostics{issue(DuplicateField, childPath)}
			}
			child, err := readValue(dec, childPath, depth+1)
			if err != nil {
				return nil, err
			}
			value[key] = child
		}
		if closeToken, err := dec.Token(); err != nil || closeToken != json.Delim('}') {
			return nil, Diagnostics{issue(InvalidJSON, path)}
		}
		return value, nil
	case '[':
		value := make([]any, 0)
		for dec.More() {
			child, err := readValue(dec, path+pointer(strconv.Itoa(len(value))), depth+1)
			if err != nil {
				return nil, err
			}
			value = append(value, child)
		}
		if closeToken, err := dec.Token(); err != nil || closeToken != json.Delim(']') {
			return nil, Diagnostics{issue(InvalidJSON, path)}
		}
		return value, nil
	default:
		return nil, Diagnostics{issue(InvalidJSON, path)}
	}
}

func validSurrogates(data []byte) bool {
	inString := false
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString || data[i] != '\\' || i+1 >= len(data) {
			continue
		}
		if data[i+1] != 'u' {
			i++
			continue
		}
		if i+6 > len(data) {
			return false
		}
		n, err := strconv.ParseUint(string(data[i+2:i+6]), 16, 16)
		if err != nil {
			return false
		}
		if n >= 0xDC00 && n <= 0xDFFF {
			return false
		}
		if n >= 0xD800 && n <= 0xDBFF {
			if i+12 > len(data) || data[i+6] != '\\' || data[i+7] != 'u' {
				return false
			}
			low, err := strconv.ParseUint(string(data[i+8:i+12]), 16, 16)
			if err != nil || low < 0xDC00 || low > 0xDFFF {
				return false
			}
			i += 6
		}
		i += 5
	}
	return true
}

func validateDocument(data []byte, definition string) error {
	value, err := parseDocument(data)
	if err != nil {
		return err
	}
	if err := schemas.Validate(definition, value); err != nil {
		return schemaDiagnostics(err)
	}
	return nil
}

func validateValue(value any, definition string) error {
	if err := validateUTF8(reflect.ValueOf(value), ""); err != nil {
		return err
	}
	data, err := json.Marshal(value)
	if err != nil {
		return Diagnostics{issue(InvalidType, "")}
	}
	return validateDocument(data, definition)
}

// Only fixed public field names can appear in diagnostics. Arbitrary JSON keys
// may themselves contain a URL or credential, so unknown keys point to their
// nearest known parent object. Array positions are generated by the parser.
func safeChildPath(parent, key string) string {
	switch key {
	case "routing_profile", "dns_profile", "rules", "match", "action", "comment", "final", "domain_resolution_mode", "domain_exact", "domain_suffix", "rule_set_ids", "ip_cidrs", "destination_ports", "network", "from", "to", "bootstrap", "resolvers", "resolver_id", "address", "bootstrap_resolver_id", "outbound", "final_resolver", "entries", "domain", "cidr", "content_hash", "platform", "local_listener", "listen", "dns_mode", "control_api", "import_method", "review_status", "reviewed_at":
		return parent + pointer(key)
	case "strategy", "default_member", "health_check", "url", "interval_ms", "timeout_ms", "tolerance_ms", "on_unavailable", "policy_group_id", "policy_overrides":
		return parent + pointer(key)
	case "schema_version", "protocol", "endpoint", "host", "port", "auth", "kind", "method", "password", "uuid", "cipher", "username", "transport", "path", "security", "mode", "server_name", "verify_certificate", "alpn", "client_fingerprint", "public_key", "short_id", "features", "udp", "multiplex", "protocol_variant", "extensions", "origin", "source_resource_id", "source_item_id", "match_method", "type", "resource_id", "builtin", "hops", "node_id", "failure_policy", "metadata", "scope_id", "revision", "name", "tags", "enabled", "security_epoch", "payload", "key", "core_family", "core_build_id", "core_build_sha256", "adapter_version", "client_preset_id", "client_preset_revision", "format", "snapshot_id", "catalog_revision", "resources", "members", "targets":
		return parent + pointer(key)
	default:
		return parent
	}
}

func validateUTF8(value reflect.Value, path string) error {
	if !value.IsValid() {
		return nil
	}
	switch value.Kind() {
	case reflect.Pointer, reflect.Interface:
		if !value.IsNil() {
			return validateUTF8(value.Elem(), path)
		}
	case reflect.String:
		if !utf8.ValidString(value.String()) {
			return Diagnostics{issue(InvalidValue, path)}
		}
	case reflect.Struct:
		for i := 0; i < value.NumField(); i++ {
			field := value.Type().Field(i)
			if field.PkgPath != "" {
				continue
			}
			name := strings.Split(field.Tag.Get("json"), ",")[0]
			if name == "-" {
				continue
			}
			if err := validateUTF8(value.Field(i), safeChildPath(path, name)); err != nil {
				return err
			}
		}
	case reflect.Slice, reflect.Array:
		for i := 0; i < value.Len(); i++ {
			if err := validateUTF8(value.Index(i), path+pointer(strconv.Itoa(i))); err != nil {
				return err
			}
		}
	}
	return nil
}

func decodePlain(data []byte, definition string, destination any) error {
	canonical, err := validatedBytes(data, definition)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(canonical, destination); err != nil {
		var diagnostics Diagnostics
		if errors.As(err, &diagnostics) {
			return diagnostics
		}
		// Never return encoding/json errors containing an input value.
		return Diagnostics{issue(InvalidType, "")}
	}
	return nil
}

// JSON Schema integers include 1.0 and 1e0. Normalize only already validated
// integer tokens so Go's int decoder accepts the same exact values. Never pass
// revision counters through float64, which loses precision above 2^53.
func validatedBytes(data []byte, definition string) ([]byte, error) {
	value, err := parseDocument(data)
	if err != nil {
		return nil, err
	}
	if err := schemas.Validate(definition, value); err != nil {
		return nil, schemaDiagnostics(err)
	}
	var normalize func(any) (any, error)
	normalize = func(value any) (any, error) {
		switch v := value.(type) {
		case json.Number:
			if n, err := v.Int64(); err == nil {
				return json.Number(strconv.FormatInt(n, 10)), nil
			}
			number, _, err := big.ParseFloat(string(v), 10, 256, big.ToNearestEven)
			if err != nil {
				return nil, Diagnostics{issue(InvalidValue, "")}
			}
			n, accuracy := number.Int64()
			if accuracy != big.Exact {
				return nil, Diagnostics{issue(InvalidValue, "")}
			}
			return json.Number(strconv.FormatInt(n, 10)), nil
		case map[string]any:
			for key, child := range v {
				next, err := normalize(child)
				if err != nil {
					return nil, err
				}
				v[key] = next
			}
		case []any:
			for index, child := range v {
				next, err := normalize(child)
				if err != nil {
					return nil, err
				}
				v[index] = next
			}
		}
		return value, nil
	}
	value, err = normalize(value)
	if err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, Diagnostics{issue(InvalidJSON, "")}
	}
	return encoded, nil
}

func safeDecodeError(err error) error {
	if err == nil {
		return nil
	}
	var diagnostics Diagnostics
	if errors.As(err, &diagnostics) {
		return diagnostics
	}
	return Diagnostics{issue(InvalidJSON, "")}
}

func schemaDiagnostics(err error) Diagnostics {
	var validationError *jsonschema.ValidationError
	if !errors.As(err, &validationError) {
		return Diagnostics{issue(InvalidSnapshot, "")}
	}
	var out Diagnostics
	var visit func(*jsonschema.ValidationError)
	visit = func(current *jsonschema.ValidationError) {
		path := pointer(current.InstanceLocation...)
		switch failure := current.ErrorKind.(type) {
		case *kind.Required:
			for _, field := range failure.Missing {
				out = append(out, issue(RequiredField, path+pointer(field)))
			}
			return
		case *kind.AdditionalProperties:
			// Do not echo unknown field names: even a property key can be a secret.
			out = append(out, issue(UnknownField, path))
			return
		}
		if len(current.Causes) != 0 {
			for _, child := range current.Causes {
				visit(child)
			}
			return
		}
		code := InvalidValue
		switch current.ErrorKind.(type) {
		case *kind.Type:
			code = InvalidType
		case *kind.Enum, *kind.Const:
			if strings.HasSuffix(path, "/schema_version") {
				code = UnsupportedVersion
			} else if strings.HasSuffix(path, "/kind") || strings.HasSuffix(path, "/mode") || strings.HasSuffix(path, "/type") {
				code = InvalidUnion
			}
		}
		out = append(out, issue(code, path))
	}
	visit(validationError)
	return stableDiagnostics(out)
}
