import { test, expect, type Page } from '@playwright/test'

const seed = JSON.parse(process.env.PROXYLOOM_M3_SEED ?? '{}') as { node: string; exit: string; chain: string; target: string; download_target: string; target_url: string }
async function login(page: Page) {
  await page.goto('/login')
  await page.locator('[name="username"]').fill(process.env.PROXYLOOM_E2E_USERNAME!)
  await page.locator('[name="password"]').fill(process.env.PROXYLOOM_E2E_PASSWORD!)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '节点库', exact: true })).toBeVisible()
}
async function headers(page: Page, revision?: string) {
  const me = await page.request.get('/api/v1/auth/me'); expect(me.status()).toBe(200)
  return { Origin: new URL(process.env.PROXYLOOM_E2E_BASE_URL!).origin, 'X-CSRF-Token': (await me.json()).data.csrf_token, 'Content-Type': 'application/json', ...(revision ? { 'If-Match': `"r${revision}"` } : {}) }
}
async function read(page: Page, path: string) { const response = await page.request.get(`/api/v1${path}`); expect(response.status()).toBe(200); return (await response.json()).data }
test.describe.configure({ mode: 'serial' })
test.beforeEach(async ({ page }) => { await login(page) })
test.afterEach(async ({ page }) => { expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0]) })

test('system settings keep conflicting drafts and expose safe audit and overview', async ({ page }) => {
  await page.goto('/overview')
  await expect(page.getByRole('heading', { name: '今日测试预算', exact: true })).toBeVisible()
  await page.goto('/system')
  const field = page.getByLabel('单次导入条数', { exact: true })
  await expect(field).toHaveValue('5000')
  await field.fill('4999')
  await page.getByRole('button', { name: '保存系统设置', exact: true }).click()
  await expect(page.getByText('设置已保存 · r2', { exact: true })).toBeVisible()
  await page.reload()
  await expect(field).toHaveValue('4999')
  const current = await read(page, '/system/settings')
  const update = await page.request.patch('/api/v1/system/settings', { headers: await headers(page, current.revision), data: { catalog_limits: { max_import_items: 4998 } } })
  expect(update.status()).toBe(200)
  await field.fill('4997')
  await page.getByRole('button', { name: '保存系统设置', exact: true }).click()
  await expect(page.getByText(/资源已被其他操作修改/)).toBeVisible()
  await expect(field).toHaveValue('4997')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '重新读取设置', exact: true }).click()
  await expect(field).toHaveValue('4998')
  await field.fill('5000')
  await page.getByRole('button', { name: '保存系统设置', exact: true }).click()
  await expect(page.getByText('设置已保存 · r4', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '审计操作', exact: true }).selectOption('settings_update')
  await page.getByRole('button', { name: '筛选审计', exact: true }).click()
  await expect(page.getByRole('cell', { name: '/catalog_limits/max_import_items', exact: true })).toHaveCount(3)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.goto('/cores')
  await expect(page.getByRole('heading', { name: '内核构建', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '架构', exact: true }).selectOption('arm64')
  await expect(page.getByRole('button', { name: '停用此构建', exact: true })).toHaveCount(3)
  await expect(page.getByText('可用 · 未验证', { exact: true })).toHaveCount(3)
})

test('batch real nodes and chains, restore by refresh, and show immutable stale history on mobile', async ({ page }) => {
  await page.goto('/tests')
  await page.getByLabel('选择 M3 第一跳', { exact: true }).check()
  await page.getByLabel('选择 M3 完整两跳', { exact: true }).check()
  await page.getByRole('button', { name: '选择测试参数', exact: true }).click()
  await page.getByLabel('登记目标', { exact: false }).selectOption(seed.target)
  await page.getByRole('button', { name: '创建测试任务', exact: true }).click()
  await expect(page).toHaveURL(/\/jobs\/[0-9a-f-]{36}$/)
  const id = new URL(page.url()).pathname.split('/').at(-1)!
  await page.reload()
  await expect(page.getByRole('heading', { name: '测试通过', exact: true })).toBeVisible({ timeout: 45000 })
  const batch = await read(page, `/jobs/${id}`)
  expect(batch.children).toHaveLength(2)
  expect(batch.children.every((job: any) => job.state === 'succeeded' && job.verdict === 'pass' && job.attempt === 1)).toBeTruthy()
  const node = await read(page, `/nodes/${seed.node}`)
  const changed = await page.request.patch(`/api/v1/nodes/${seed.node}`, { headers: await headers(page, node.metadata.revision), data: { name: 'M3 第一跳 · 已编辑' } })
  expect(changed.status()).toBe(200)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`/test-results?subject_id=${seed.chain}`)
  await expect(page.getByText('历史修订', { exact: true })).toBeVisible()
  await expect(page.getByText('有效 3 / 3，失败 0', { exact: true })).toBeVisible()
  await page.getByText('阶段耗时与证据关联', { exact: true }).click()
  await expect(page.getByText('完整依赖', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('link', { name: '按当前修订重新测试', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('选择 M3 完整两跳', { exact: true })).toBeChecked()
})

test('download SSE reconnect restores snapshots and cancellation settles without repeating the download', async ({ page }) => {
  await page.goto(`/tests?subject=${seed.chain}`)
  await page.getByRole('button', { name: '选择测试参数', exact: true }).click()
  await page.getByRole('combobox', { name: '测试类型', exact: true }).selectOption('download_throughput')
  await page.getByLabel('登记目标', { exact: false }).selectOption(seed.download_target)
  await page.getByRole('button', { name: '创建测试任务', exact: true }).click()
  await expect(page).toHaveURL(/\/jobs\/[0-9a-f-]{36}$/)
  const id = new URL(page.url()).pathname.split('/').at(-1)!
  let streams = 0
  page.on('request', request => { if (request.url().endsWith('/events')) streams++ })
  await expect(page.getByText('限额下载 · 0 / 1', { exact: true })).toBeVisible({ timeout: 30000 })
  const beforeReconnect = streams
  await page.context().setOffline(true)
  await page.waitForTimeout(500)
  await page.context().setOffline(false)
  await expect(page.getByText('实时连接已建立', { exact: true })).toBeVisible({ timeout: 15000 })
  await expect.poll(() => streams, { timeout: 5000 }).toBeGreaterThan(beforeReconnect)
  const start = Date.now()
  await page.getByRole('button', { name: '取消整个批次', exact: true }).click()
  await expect(page.getByRole('heading', { name: '已取消', exact: true })).toBeVisible({ timeout: 5500 })
  expect(Date.now() - start).toBeLessThan(5500)
  await page.reload()
  await expect(page.getByRole('heading', { name: '已取消', exact: true })).toBeVisible()
  const batch = await read(page, `/jobs/${id}`)
  expect(batch.children[0].attempt).toBe(1)
  const results = await read(page, `/test-results?subject_id=${seed.chain}&type=download_throughput`)
  expect(results).toHaveLength(1)
  expect(results[0].state).toBe('canceled')
  expect(results[0].metrics.throughput_mbps).toBeUndefined()
})

test('register an HTTP target through the Chinese keyboard-accessible form and reject protected addresses', async ({ page }) => {
  await page.goto('/test-targets')
  await page.getByLabel('名称', { exact: true }).fill('浏览器受控目标')
  await page.getByLabel('HTTP(S) URL', { exact: true }).fill(`${seed.target_url}/check`)
  await page.getByRole('button', { name: '保存目标', exact: true }).click()
  await expect(page.getByText('测试目标已保存。实际测试仍会校验证书、状态与响应特征。', { exact: true })).toBeVisible()
  await expect(page.getByRole('row', { name: /浏览器受控目标/ })).toBeVisible()
  const response = await page.request.post('/api/v1/test-targets', { headers: { ...await headers(page), 'Idempotency-Key': crypto.randomUUID() }, data: { name: 'forbidden loopback', target: { url: 'http://127.0.0.1:22', allowed_types: ['connectivity'], expected_response: { status_codes: [200], max_response_bytes: 64, egress_ip_response: false }, limits: { duration_ms: 1000, max_bytes: 64 }, permission_basis: 'self_owned', redirect_policy: 'deny', verify_certificate: true, compression: 'disabled' } } })
  expect(response.status()).toBe(422)
})
