package importparse

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"testing"
)

func FuzzParseURI(f *testing.F) {
	for _, seed := range []string{"", share("http", "edge.invalid"), share("vless", "edge.invalid:443"), share("ss", ""), share("vmess", base64.StdEncoding.EncodeToString([]byte(`{"v":"2"}`))), "\xff"} {
		f.Add(seed)
	}
	f.Fuzz(func(t *testing.T, raw string) {
		candidate := ParseURI(raw)
		if candidate.Valid() {
			if len(raw) > MaxURIBytes || candidate.Node.Validate() != nil {
				t.Fatal("valid candidate violated URI budget or IR contract")
			}
		} else if candidate.Node != nil || len(candidate.Diagnostics) == 0 {
			t.Fatal("invalid candidate retained executable data or lacked a diagnostic")
		}
		first, err := json.Marshal(candidate)
		second, nextErr := json.Marshal(ParseURI(raw))
		if err != nil || nextErr != nil || string(first) != string(second) {
			t.Fatal("URI parsing was not deterministic or serializable")
		}
	})
}

func FuzzParseBatch(f *testing.F) {
	for _, seed := range [][]byte{nil, []byte(share("http", "edge.invalid")), []byte("proxies: []"), []byte(base64.StdEncoding.EncodeToString([]byte(share("unknown", "edge.invalid")))), {0x1f, 0x8b}} {
		f.Add(seed, uint8(0))
	}
	f.Fuzz(func(t *testing.T, input []byte, formatIndex uint8) {
		// Dedicated tests cover 10 MiB/5000 entry boundaries. Keep mutation
		// feedback useful and bounded for arbitrary fuzzer-generated bytes.
		if len(input) > 64*1024 {
			t.Skip()
		}
		format := []string{FormatAuto, FormatText, FormatBase64}[int(formatIndex)%3]
		result, err := Parse(context.Background(), format, input)
		if err != nil {
			if len(result.Candidates) != 0 {
				t.Fatal("batch failure returned a truncated preview")
			}
			return
		}
		if len(result.Candidates) == 0 || len(result.Candidates) > MaxEntries || result.Base64Layers > MaxBase64Layers {
			t.Fatal("batch result violated its resource contract")
		}
		lastLine := 0
		for index, candidate := range result.Candidates {
			if candidate.Index != index || candidate.Line <= lastLine || candidate.Valid() && candidate.Node.Validate() != nil || !candidate.Valid() && candidate.Node != nil {
				t.Fatal("candidate positions or typed validity were inconsistent")
			}
			lastLine = candidate.Line
		}
	})
}
