<script setup lang="ts">
import type { Schema } from '../api/client'
import type { NetworkOptions } from '../domain/network-draft'
import { moveRule, newDNSRule } from '../domain/network-draft'
import TargetSelect from './TargetSelect.vue'
import MatchFields from './MatchFields.vue'
const draft = defineModel<Schema<'DNSProfile'>>({ required: true })
defineProps<{ options: NetworkOptions }>()
function nextID(prefix: string) {
  let number = 1
  while ([...draft.value.bootstrap, ...draft.value.resolvers].some(item => item.resolver_id === `${prefix}_${number}`)) number++
  return `${prefix}_${number}`
}
function rename(index: number, value: string, bootstrap = false) {
  const resolver = (bootstrap ? draft.value.bootstrap : draft.value.resolvers)[index]
  const old = resolver.resolver_id; resolver.resolver_id = value
  if (bootstrap) { for (const item of draft.value.resolvers) if (item.kind === 'https' && item.bootstrap_resolver_id === old) item.bootstrap_resolver_id = value }
  else { if (draft.value.final_resolver === old) draft.value.final_resolver = value; for (const rule of draft.value.rules) if (rule.resolver_id === old) rule.resolver_id = value }
}
function changeBootstrap(index: number, kind: string) {
  const resolver_id = draft.value.bootstrap[index].resolver_id
  draft.value.bootstrap[index] = kind === 'udp' ? { resolver_id, kind: 'udp', address: '', port: 53 } : { resolver_id, kind: 'local' }
}
function changeResolver(index: number, kind: string) {
  const resolver_id = draft.value.resolvers[index].resolver_id
  draft.value.resolvers[index] = kind === 'udp' ? { resolver_id, kind: 'udp', address: '', port: 53, outbound: { type: 'builtin', builtin: 'reject' } }
    : kind === 'https' ? { resolver_id, kind: 'https', url: '', bootstrap_resolver_id: draft.value.bootstrap[0]?.resolver_id ?? '', outbound: { type: 'builtin', builtin: 'reject' } }
      : { resolver_id, kind: 'local' }
}
const bootstrapUsed = (id: string) => draft.value.resolvers.some(item => item.kind === 'https' && item.bootstrap_resolver_id === id)
const resolverUsed = (id: string) => draft.value.final_resolver === id || draft.value.rules.some(rule => rule.resolver_id === id)
</script>
<template>
  <p class="notice info">解析器使用本配置内的稳定 ID。重命名会同步更新本表单中的引用；删除前需先替换引用。引导、DNS 与出站依赖的循环由服务端检查。</p>
  <p class="hint">第一项引导解析器用于节点地址；HTTPS 解析器使用各自选择的引导项。不会并行查询或自动回退；目标内核不能保持该依赖时会返回兼容诊断。</p>
  <div class="section-heading"><h2>引导解析器</h2><button type="button" class="secondary" :disabled="draft.bootstrap.length >= 32" @click="draft.bootstrap.push({ resolver_id: nextID('bootstrap'), kind: 'local' })">添加引导解析器</button></div>
  <fieldset v-for="(resolver, index) in draft.bootstrap" :key="index"><legend>引导解析器 {{ index + 1 }}</legend><div class="form-grid"><label>引导解析器 ID<input :value="resolver.resolver_id" required pattern="[a-z][a-z0-9_-]{0,63}" maxlength="64" :data-field="`/dns_profile/bootstrap/${index}/resolver_id`" @change="rename(index, ($event.target as HTMLInputElement).value, true)" /></label><label>引导类型<select :value="resolver.kind" @change="changeBootstrap(index, ($event.target as HTMLSelectElement).value)"><option value="local">本机系统解析</option><option value="udp">UDP 字面 IP 地址</option></select></label><template v-if="resolver.kind === 'udp'"><label>引导 IP 地址<input v-model="resolver.address" required :data-field="`/dns_profile/bootstrap/${index}/address`" placeholder="192.0.2.53" /></label><label>引导端口<input v-model.number="resolver.port" type="number" min="1" max="65535" required :data-field="`/dns_profile/bootstrap/${index}/port`" /></label></template></div><div class="actions orchestration-gap"><span v-if="bootstrapUsed(resolver.resolver_id)" class="hint">被 HTTPS 解析器引用</span><button type="button" class="text-button" :disabled="draft.bootstrap.length <= 1 || bootstrapUsed(resolver.resolver_id)" :aria-label="`移除引导解析器 ${index + 1}`" @click="draft.bootstrap.splice(index, 1)">移除</button></div></fieldset>
  <div class="section-heading"><h2>主解析器</h2><button type="button" class="secondary" :disabled="draft.resolvers.length >= 32" @click="draft.resolvers.push({ resolver_id: nextID('resolver'), kind: 'local' })">添加主解析器</button></div>
  <fieldset v-for="(resolver, index) in draft.resolvers" :key="index"><legend>主解析器 {{ index + 1 }}</legend><div class="form-grid"><label>解析器 ID<input :value="resolver.resolver_id" required pattern="[a-z][a-z0-9_-]{0,63}" maxlength="64" :data-field="`/dns_profile/resolvers/${index}/resolver_id`" @change="rename(index, ($event.target as HTMLInputElement).value)" /></label><label>解析类型<select :value="resolver.kind" @change="changeResolver(index, ($event.target as HTMLSelectElement).value)"><option value="local">本机系统解析</option><option value="udp">UDP</option><option value="https">HTTPS（DoH）</option></select></label><template v-if="resolver.kind === 'udp'"><label>DNS IP 地址<input v-model="resolver.address" required :data-field="`/dns_profile/resolvers/${index}/address`" placeholder="192.0.2.53" /></label><label>DNS 端口<input v-model.number="resolver.port" type="number" min="1" max="65535" required :data-field="`/dns_profile/resolvers/${index}/port`" /></label></template><template v-if="resolver.kind === 'https'"><label>HTTPS 解析地址<input v-model="resolver.url" type="url" required maxlength="2048" :data-field="`/dns_profile/resolvers/${index}/url`" placeholder="https://example.com/dns-query" /></label><label>引导解析器<select v-model="resolver.bootstrap_resolver_id" required :data-field="`/dns_profile/resolvers/${index}/bootstrap_resolver_id`"><option value="" disabled>选择引导解析器</option><option v-if="resolver.bootstrap_resolver_id && !draft.bootstrap.some(item => item.resolver_id === resolver.bootstrap_resolver_id)" :value="resolver.bootstrap_resolver_id" disabled>未声明 · {{ resolver.bootstrap_resolver_id }}</option><option v-for="item in draft.bootstrap" :key="item.resolver_id" :value="item.resolver_id">{{ item.resolver_id }}</option></select></label></template><TargetSelect v-if="resolver.kind !== 'local'" v-model="resolver.outbound" label="DNS 出站动作" :options="options.targets" :path="`/dns_profile/resolvers/${index}/outbound`" /></div><div class="actions orchestration-gap"><span v-if="resolverUsed(resolver.resolver_id)" class="hint">被默认解析器或规则引用</span><button type="button" class="text-button" :disabled="draft.resolvers.length <= 1 || resolverUsed(resolver.resolver_id)" :aria-label="`移除主解析器 ${index + 1}`" @click="draft.resolvers.splice(index, 1)">移除</button></div></fieldset>
  <fieldset><legend>默认解析器</legend><label>未命中规则时使用<select v-model="draft.final_resolver" required data-field="/dns_profile/final_resolver"><option value="" disabled>选择主解析器</option><option v-if="draft.final_resolver && !draft.resolvers.some(item => item.resolver_id === draft.final_resolver)" :value="draft.final_resolver" disabled>未声明 · {{ draft.final_resolver }}</option><option v-for="resolver in draft.resolvers" :key="resolver.resolver_id" :value="resolver.resolver_id">{{ resolver.resolver_id }}</option></select></label></fieldset>
  <div class="section-heading"><div><h2>有序 DNS 规则</h2><p class="hint">首条命中生效。不同字段 AND，同字段多项 OR。</p></div><button type="button" class="secondary" :disabled="draft.rules.length >= 1000" @click="draft.rules.push(newDNSRule(draft.final_resolver))">添加 DNS 规则</button></div>
  <fieldset v-for="(rule, index) in draft.rules" :key="index"><legend>DNS 规则 {{ index + 1 }}</legend><div class="section-heading"><label class="checkbox-label"><input v-model="rule.enabled" type="checkbox" />启用此规则</label><div class="actions"><button type="button" class="text-button" :disabled="index === 0" :aria-label="`上移 DNS 规则 ${index + 1}`" @click="moveRule(draft.rules, index, -1)">上移</button><button type="button" class="text-button" :disabled="index === draft.rules.length - 1" :aria-label="`下移 DNS 规则 ${index + 1}`" @click="moveRule(draft.rules, index, 1)">下移</button><button type="button" class="text-button" :aria-label="`移除 DNS 规则 ${index + 1}`" @click="draft.rules.splice(index, 1)">移除</button></div></div><div class="form-grid"><label>备注<input v-model="rule.comment" maxlength="500" :data-field="`/dns_profile/rules/${index}/comment`" /></label><label>命中解析器<select v-model="rule.resolver_id" required :data-field="`/dns_profile/rules/${index}/resolver_id`"><option value="" disabled>选择主解析器</option><option v-if="rule.resolver_id && !draft.resolvers.some(item => item.resolver_id === rule.resolver_id)" :value="rule.resolver_id" disabled>未声明 · {{ rule.resolver_id }}</option><option v-for="resolver in draft.resolvers" :key="resolver.resolver_id" :value="resolver.resolver_id">{{ resolver.resolver_id }}</option></select></label></div><MatchFields v-model="rule.match" :rule-sets="options.ruleSets" :path="`/dns_profile/rules/${index}/match`" /></fieldset>
</template>
