<script setup lang="ts">
import type { Schema } from '../api/client'
import type { RuleSetOption } from '../domain/network-draft'
const match = defineModel<Schema<'RouteMatch'>>({ required: true })
defineProps<{ routing?: boolean; ruleSets: RuleSetOption[]; path: string }>()
function setLines(key: 'domain_exact' | 'domain_suffix' | 'ip_cidrs', value: string) { match.value[key] = value.split(/[\n,，]/).map(item => item.trim()).filter(Boolean) }
function toggleSet(id: string, enabled: boolean) { match.value.rule_set_ids = enabled ? [...(match.value.rule_set_ids ?? []), id] : match.value.rule_set_ids?.filter(value => value !== id) }
function toggleNetwork(value: 'tcp' | 'udp', enabled: boolean) { match.value.network = enabled ? [...(match.value.network ?? []), value] : match.value.network?.filter(item => item !== value) }
</script>
<template>
  <div class="form-grid"><label>精确域名（每行一个）<textarea :value="match.domain_exact?.join('\n') ?? ''" :data-field="`${path}/domain_exact`" placeholder="example.com" @change="setLines('domain_exact', ($event.target as HTMLTextAreaElement).value)" /></label><label>域名后缀（每行一个）<textarea :value="match.domain_suffix?.join('\n') ?? ''" :data-field="`${path}/domain_suffix`" placeholder="example.com" @change="setLines('domain_suffix', ($event.target as HTMLTextAreaElement).value)" /></label><label v-if="routing" class="span-2">目标 IP 网段（每行一个 CIDR）<textarea :value="match.ip_cidrs?.join('\n') ?? ''" :data-field="`${path}/ip_cidrs`" placeholder="192.0.2.0/24" @change="setLines('ip_cidrs', ($event.target as HTMLTextAreaElement).value)" /></label></div>
  <p class="hint">域名保存为小写 IDNA ASCII；后缀包含该域名本身及其子域名。不同字段为 AND，同一字段内多项为 OR；至少填写一个条件。</p>
  <fieldset v-if="routing"><legend>传输与端口条件</legend><div class="inline-form"><label v-for="network in (['tcp', 'udp'] as const)" :key="network" class="checkbox-label"><input type="checkbox" :checked="match.network?.includes(network)" @change="toggleNetwork(network, ($event.target as HTMLInputElement).checked)" />{{ network.toUpperCase() }}</label></div><div v-for="(range, index) in match.destination_ports ?? []" :key="index" class="inline-form orchestration-gap"><label>起始端口<input v-model.number="range.from" type="number" min="1" max="65535" required :data-field="`${path}/destination_ports/${index}/from`" /></label><label>结束端口<input v-model.number="range.to" type="number" min="1" max="65535" required :data-field="`${path}/destination_ports/${index}/to`" /></label><button type="button" class="text-button" @click="match.destination_ports?.splice(index, 1)">移除此端口范围</button></div><button type="button" class="secondary orchestration-gap" :disabled="(match.destination_ports?.length ?? 0) >= 100" @click="(match.destination_ports ??= []).push({ from: 443, to: 443 })">添加端口范围</button></fieldset>
  <fieldset><legend>引用规则集</legend><p v-if="!ruleSets.length" class="hint">暂无已启用规则集，可先在规则集管理中创建。</p><label v-for="option in ruleSets" :key="option.id" class="checkbox-label"><input type="checkbox" :checked="match.rule_set_ids?.includes(option.id)" :data-field="`${path}/rule_set_ids`" @change="toggleSet(option.id, ($event.target as HTMLInputElement).checked)" />{{ option.name }} · {{ option.id }}</label><div v-for="id in match.rule_set_ids?.filter(id => !ruleSets.some(option => option.id === id))" :key="id" class="notice warning">不可用规则集 · {{ id }} <button type="button" class="text-button" @click="toggleSet(id, false)">移除引用</button></div></fieldset>
</template>
