<script setup lang="ts">
import type { NetworkResource } from '../domain/network-draft'
import { formatRuleSetText } from '../domain/network-form'
import MatchSummary from './MatchSummary.vue'
import TargetSummary from './TargetSummary.vue'
defineProps<{ resource: NetworkResource }>()
</script>
<template>
  <template v-if="'routing_profile' in resource"><section class="panel"><h2>路由行为</h2><dl class="detail-list"><dt>域名解析模式</dt><dd>{{ resource.routing_profile.domain_resolution_mode === 'preserve_domain' ? '保留域名，不为 IP 规则额外解析' : '通过显式 DNS 配置解析后匹配 IP 规则' }}</dd><dt>最终动作</dt><dd><TargetSummary :target="resource.routing_profile.final" /></dd></dl><p class="hint">首条命中生效。不同字段 AND，同字段多项 OR。</p></section><section v-for="(rule, index) in resource.routing_profile.rules" :key="index" class="panel"><h2>路由规则 {{ index + 1 }} · {{ rule.enabled ? '已启用' : '已停用' }}</h2><p v-if="rule.comment">{{ rule.comment }}</p><MatchSummary :match="rule.match" /><div class="section-heading"><strong>命中动作</strong><TargetSummary :target="rule.action" /></div></section></template>
  <template v-else-if="'dns_profile' in resource"><section class="panel"><h2>DNS 解析行为</h2><p>默认解析器：<strong>{{ resource.dns_profile.final_resolver }}</strong></p><p class="hint">规则按顺序匹配，首条命中生效；不同字段 AND，同字段多项 OR。</p></section><section class="panel"><h2>引导解析器</h2><dl class="detail-list"><template v-for="resolver in resource.dns_profile.bootstrap" :key="resolver.resolver_id"><dt>{{ resolver.resolver_id }}</dt><dd>{{ resolver.kind === 'local' ? '本机系统解析' : `UDP · ${resolver.address}:${resolver.port}` }}</dd></template></dl></section><section v-for="resolver in resource.dns_profile.resolvers" :key="resolver.resolver_id" class="panel"><h2>主解析器 · {{ resolver.resolver_id }}</h2><dl class="detail-list"><dt>类型</dt><dd>{{ resolver.kind === 'local' ? '本机系统解析' : resolver.kind === 'udp' ? 'UDP' : 'HTTPS（DoH）' }}</dd><template v-if="resolver.kind === 'udp'"><dt>地址</dt><dd>{{ resolver.address }}:{{ resolver.port }}</dd></template><template v-if="resolver.kind === 'https'"><dt>地址</dt><dd>{{ resolver.url }}</dd><dt>引导解析器</dt><dd>{{ resolver.bootstrap_resolver_id }}</dd></template><template v-if="resolver.kind !== 'local'"><dt>出站动作</dt><dd><TargetSummary :target="resolver.outbound" /></dd></template></dl></section><section v-for="(rule, index) in resource.dns_profile.rules" :key="index" class="panel"><h2>DNS 规则 {{ index + 1 }} · {{ rule.enabled ? '已启用' : '已停用' }}</h2><p v-if="rule.comment">{{ rule.comment }}</p><MatchSummary :match="rule.match" /><p>命中解析器：<strong>{{ rule.resolver_id }}</strong></p></section></template>
  <section v-else class="panel"><h2>规范化规则条目</h2><p>共 {{ resource.rule_set.entries.length }} 条 · domain_cidr_text</p><dl class="detail-list"><dt>内容摘要</dt><dd class="mono">{{ resource.rule_set.content_hash }}</dd></dl><pre class="rule-preview">{{ formatRuleSetText(resource.rule_set.entries.slice(0, 100)) }}</pre><p v-if="resource.rule_set.entries.length > 100" class="hint">此处显示前 100 条，编辑页可读取全部条目。</p></section>
</template>
